local effectId = {
	NULL = 0,
	PSISTORMPERSISTENT = 1,
	GUARDIANSHIELDPERSISTENT = 2,
	TEMPORALFIELDGROWINGBUBBLECREATEPERSISTENT = 3,
	TEMPORALFIELDAFTERBUBBLECREATEPERSISTENT = 4,
	THERMALLANCESFORWARD = 5,
	SCANNERSWEEP = 6,
	NUKEPERSISTENT = 7,
	LIBERATORTARGETMORPHDELAYPERSISTENT = 8,
	LIBERATORTARGETMORPHPERSISTENT = 9,
	BLINDINGCLOUDCP = 10,
	RAVAGERCORROSIVEBILECP = 11,
	LURKERMP = 12,
}

return effectId
